import { Page, test as base } from "@playwright/test";
import * as fs from "fs";

const API = "http://localhost:8000";

/**
 * Read the E2E JWT token generated by scripts/e2e-setup.sh.
 * Falls back to a fake token for mock-mode tests.
 */
function readToken(): string {
  try {
    return fs.readFileSync("/tmp/e2e-token.txt", "utf-8").trim();
  } catch {
    console.warn("⚠️  /tmp/e2e-token.txt not found — tests will fail on real API");
    return "missing-e2e-token";
  }
}

export type AuthOptions = {
  /** If true, mock the API endpoints instead of using the real backend */
  mockMode?: boolean;
};

export const test = base.extend<{ auth: AuthOptions }>({
  auth: [
    async ({ page }, use) => {
      const token = readToken();

      // Inject the real JWT into localStorage before any page load
      await page.addInitScript((t) => {
        localStorage.setItem("token", t);
      }, token);

      await use({ mockMode: false });
    },
    { auto: true },
  ],
});

export { expect } from "@playwright/test";

/**
 * Pass through: don't mock anything, use the real backend.
 * This is the default — we keep this function for consistency
 * with mock-based tests.
 */
export async function useRealApi() {
  // No-op: just use the real backend
}

/**
 * Mock a REST API endpoint (for mock-mode tests only).
 */
export async function mockApi(
  page: Page,
  urlPattern: string | RegExp,
  response: unknown,
  method?: string,
) {
  await page.route(urlPattern, async (route) => {
    if (method && route.request().method() !== method) {
      await route.fallback();
      return;
    }
    const status = method?.toUpperCase() === "POST" ? 201 : 200;
    await route.fulfill({ status, contentType: "application/json", body: JSON.stringify(response) });
  });
}
